/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_endress_cdiprotocol_CdiProtocolJni */

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jstring JNICALL Java_com_example_mybleapp_MainActivity_hello(JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif

